import * as THREE from 'three';

import fieldVert from '../../shaders/correction-field.vert.glsl?raw';
import fieldFrag from '../../shaders/correction-field.frag.glsl?raw';

/**
 * FieldModel — the apparition.
 *
 * One screen-filling draw. Everything visible is a level set of a distance
 * field marched per pixel: there is no geometry in the scene graph, no vertex
 * buffer describing a form, and nothing that can be recognised as the material
 * the thing is made from.
 *
 * That last clause is the whole reason this file exists. The hero has been
 * rebuilt five times — filaments, a swept surface, a scatter, lamellae,
 * plates — and every version died the same way: the primitive stayed visible,
 * so the eye identified the material and classified the object before it could
 * feel anything about it. Founder ruling, 2026-08-12: stop designing objects,
 * design an apparition generated by mathematics.
 *
 * The trade this makes, stated plainly: cost moves from vertex count to pixel
 * count, so quality tiers scale the step budget rather than the element count,
 * and the whole thing lives or dies on the distance estimator staying cheap.
 */

export interface FieldModelOptions {
  /** Step budget for the march. The quality tier's only lever. */
  steps?: number;
}

/**
 * How far the fold contracts space each pass.
 *
 * Above about two the recursion tears itself apart within four iterations and
 * the estimator stops bounding anything; below about 1.4 the passes stop adding
 * detail and it reads as one smooth blob. The useful window is narrow.
 */
export const SCALE = 0.62;

/** How far each fold is offset before it mirrors. Zero here is a kaleidoscope. */
export const FOLD_OFFSET = 0.35;

/** The primitive at the bottom of the recursion, and how soft its corners are. */
export const BOX = { x: 0.62, y: 0.94, z: 0.51 };
export const ROUND = 0.14;

/** Large-scale bend applied before the recursion starts. */
export const WARP = 2.2;

/** Where the absence sits, and how large it is. Off-centre by mandate. */
export const CORE = { x: 1.55, y: 0.85, z: -0.7 };
export const CORE_RADIUS = 2.6;

/**
 * The dead star's crazing: how fine the fissure network is, how deep the
 * cracks cut, and how much residual heat sits in them.
 */
export const FISSURE = { scale: 1.45, depth: 0.16, heat: 1.6 };

/**
 * How the field answers a pointer held over it: how far attention reaches,
 * how hard the fissures warm under it, and how strong the cool edge is.
 *
 * Bracketed by two failures rather than chosen. At gain 4.2 across all the
 * structure the hovered region became a blue-white mass with none of the dead
 * star's material left in it — measurably a success and visibly a disaster. At
 * 1.15 on the fissures alone it was indistinguishable from rest. These sit
 * between, and they are on sliders because the right value is a judgement, not
 * a measurement.
 */
export const HOVER_RADIUS = 0.42;
export const HOVER_GAIN = 2.6;
export const HOVER_FRINGE = 0.7;

/** How tightly the aureole gathers against the absence's boundary. */
export const AUREOLE = 1.15;

/** Overall emission, and how sharply light concentrates at a boundary. */
export const GLOW = 2.4;
export const DENSITY = 9.0;

export class FieldModel {
  readonly group = new THREE.Group();

  private readonly material: THREE.ShaderMaterial;
  private readonly uniforms: Record<string, THREE.IUniform>;
  private readonly basis = new THREE.Matrix4();
  private readonly right = new THREE.Vector3();
  private readonly up = new THREE.Vector3();
  private readonly forward = new THREE.Vector3();

  constructor(options: FieldModelOptions = {}) {
    this.uniforms = {
      uResolution: { value: new THREE.Vector2(1, 1) },
      uCamPos: { value: new THREE.Vector3() },
      uCamRight: { value: new THREE.Vector3(1, 0, 0) },
      uCamUp: { value: new THREE.Vector3(0, 1, 0) },
      uCamForward: { value: new THREE.Vector3(0, 0, -1) },
      uTanFov: { value: Math.tan((32 * Math.PI) / 360) },
      uTime: { value: 0 },
      uBreath: { value: 0 },
      uSteps: { value: options.steps ?? 128 },

      uRecord: { value: new THREE.Color('#e7dcba') },
      uWorld: { value: new THREE.Color('#4dd0ff') },
      uConsequence: { value: new THREE.Color('#a45fd6') },

      uScale: { value: SCALE },
      uFoldOffset: { value: FOLD_OFFSET },
      uBox: { value: new THREE.Vector3(BOX.x, BOX.y, BOX.z) },
      uRound: { value: ROUND },
      uWarp: { value: WARP },

      uCore: { value: new THREE.Vector3(CORE.x, CORE.y, CORE.z) },
      uCoreRadius: { value: CORE_RADIUS },
      uFissureScale: { value: FISSURE.scale },
      uFissureDepth: { value: FISSURE.depth },
      uHeat: { value: FISSURE.heat },
      uHover: { value: new THREE.Vector2(0, 0) },
      uHoverStrength: { value: 0 },
      uHoverRadius: { value: HOVER_RADIUS },
      uHoverGain: { value: HOVER_GAIN },
      uHoverFringe: { value: HOVER_FRINGE },
      uAureole: { value: AUREOLE },
      uGlow: { value: GLOW },
      uDensity: { value: DENSITY },
      uExposure: { value: 1 },
    };

    this.material = new THREE.ShaderMaterial({
      glslVersion: THREE.GLSL3,
      vertexShader: fieldVert,
      fragmentShader: fieldFrag,
      uniforms: this.uniforms,
      depthTest: false,
      depthWrite: false,
    });

    // A single oversized triangle rather than a quad: one primitive, no seam
    // across the diagonal, and no interpolation discontinuity down the middle
    // of the frame.
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute(
      'position',
      new THREE.BufferAttribute(new Float32Array([-1, -1, 0, 3, -1, 0, -1, 3, 0]), 3)
    );

    const screen = new THREE.Mesh(geometry, this.material);
    screen.frustumCulled = false;
    this.group.add(screen);
  }

  /**
   * The camera, as a basis rather than a projection.
   *
   * The march needs an origin and three axes; a projection matrix would have to
   * be inverted per pixel to recover exactly that.
   */
  setCamera(camera: THREE.PerspectiveCamera): void {
    this.basis.extractRotation(camera.matrixWorld);
    this.right.set(1, 0, 0).applyMatrix4(this.basis);
    this.up.set(0, 1, 0).applyMatrix4(this.basis);
    this.forward.set(0, 0, -1).applyMatrix4(this.basis);

    (this.uniforms.uCamPos.value as THREE.Vector3).copy(camera.position);
    (this.uniforms.uCamRight.value as THREE.Vector3).copy(this.right);
    (this.uniforms.uCamUp.value as THREE.Vector3).copy(this.up);
    (this.uniforms.uCamForward.value as THREE.Vector3).copy(this.forward);
    this.uniforms.uTanFov.value = Math.tan((camera.fov * Math.PI) / 360);
  }

  setSize(width: number, height: number): void {
    (this.uniforms.uResolution.value as THREE.Vector2).set(width, height);
  }

  /** Step budget, from the quality tier. */
  setSteps(steps: number): void {
    this.uniforms.uSteps.value = Math.max(24, Math.min(256, Math.round(steps)));
  }

  /**
   * The only thing moving in the approved state.
   *
   * It drives the fold offset, so the form reorganises very slightly rather
   * than drifting through space. A field this large that translated would read
   * as a camera move; a field that reorganises reads as breathing.
   */
  setTime(seconds: number): void {
    this.uniforms.uTime.value = seconds;
    this.uniforms.uBreath.value = Math.sin(seconds * 0.11) * 0.6 + Math.sin(seconds * 0.07) * 0.4;
  }

  /**
   * Where the pointer is, and how far the field has come up to meet it.
   *
   * Eased by the caller rather than here: the strength is a property of the
   * visit, not of the material, and the render loop is the only thing that
   * knows how much time has passed.
   */
  setHover(x: number, y: number, strength: number): void {
    (this.uniforms.uHover.value as THREE.Vector2).set(x, y);
    this.uniforms.uHoverStrength.value = Math.max(0, Math.min(1, strength));
  }

  /** Cold-open reveal, and the machine-off cut. */
  setExposure(value: number): void {
    this.uniforms.uExposure.value = value;
  }

  /** Development only: the field's numbers, live. */
  tune(patch: Record<string, number>): void {
    for (const [key, value] of Object.entries(patch)) {
      const uniform = this.uniforms[key];
      if (uniform) uniform.value = value;
    }
  }

  dispose(): void {
    this.material.dispose();
    this.group.traverse((object) => {
      if (object instanceof THREE.Mesh) object.geometry.dispose();
    });
  }
}
