/**
 * Generates the static fallback poster — ENTITY v7, the crowned
 * convergence.
 *
 * The sealed crown front-on: jagged obsidian shards in an irregular
 * top-heavy wreath, the recessed cyan core burning in the throat, the
 * amber halo tilted above the apex. Derived from the same deterministic
 * rand() and placement logic as LatticeModel so the fallback stays the
 * same object as the live one.
 *
 *   node tools/poster.mjs
 */
import { writeFile } from 'node:fs/promises';

function rand(seed) {
  const v = Math.sin(seed * 127.1 + 311.7) * 43758.5453;
  return v - Math.floor(v);
}

// --- Projection ----------------------------------------------------------
const W = 1600;
const H = 900;
const CX = 800;
const CY = 448;
const SCALE = 86;
const NL = String.fromCharCode(10);

const px = (x) => (CX + x * SCALE).toFixed(1);
const py = (y) => (CY - y * SCALE).toFixed(1);

/**
 * One jagged shard polygon, echoing LatticeModel's shard():
 * irregular 5/6-gon, spike at vertex 0 pointing outward, inner
 * vertices jitter-capped. The 3D lean is approximated by squashing
 * the radial axis — foreshortening, the composition's real worker.
 */
function shardPoints(seed, length, width, theta, radius, squash) {
  const n = 5 + Math.floor(rand(seed * 3.1) * 2);
  const cos = Math.cos(theta);
  const sin = Math.sin(theta);
  const pts = [];
  for (let i = 0; i < n; i++) {
    const a = (i / n) * Math.PI * 2;
    const inner = Math.cos(a) < -0.2;
    const jitter = inner
      ? 0.72 + rand(seed * 9.3 + i * 2.7) * 0.23
      : 0.72 + rand(seed * 9.3 + i * 2.7) * 0.56;
    const spike = i === 0 ? 1.45 : 1.0;
    const lx = Math.cos(a) * length * 0.5 * jitter * spike * squash;
    const ly = Math.sin(a) * width * 0.5 * jitter * (i === 0 ? 0.72 : 1.0);
    // Rotate the local frame so +X points along theta, then place.
    const x = radius * Math.cos(theta) + lx * cos - ly * sin;
    const y = radius * Math.sin(theta) + lx * sin + ly * cos;
    pts.push([x, y]);
  }
  return pts;
}

function poly(pts, fill, fillOpacity, stroke, strokeOpacity, strokeWidth = 1.1) {
  const d = pts.map(([x, y], i) => `${i ? 'L' : 'M'}${px(x)} ${py(y)}`).join(' ') + ' Z';
  return `<path d="${d}" fill="${fill}" fill-opacity="${fillOpacity}" stroke="${stroke}" stroke-opacity="${strokeOpacity}" stroke-width="${strokeWidth}" stroke-linejoin="round"/>`;
}

const gs = 2.3; // near gate seed base, matches buildCrown(0, …)

// Coherent armour: seven majors on a near-regular heptagon with seven
// half-scale infill shards seated behind the gaps — same constants as
// LatticeModel's buildCrown.
const majors = [];
const minors = [];
const STEP = (Math.PI * 2) / 7;
for (let i = 0; i < 7; i++) {
  const seed = rand(gs + i * 3.3);
  const theta = i * STEP + Math.PI / 2 + (rand(gs + i * 7.7) - 0.5) * 0.14;
  const topness = Math.sin(theta) * 0.5 + 0.5;
  const scale = 0.98 + topness * 0.2 + seed * 0.06;
  const radius = 2.0 + (rand(gs + i * 11.3) - 0.5) * 0.25;
  majors.push(
    poly(shardPoints(gs + i * 13.7, 3.2 * scale, 2.5 * scale, theta, radius, 0.8), '#0d1420', 1, '#8fd8f0', 0.34)
  );
  const theta2 = theta + STEP * 0.5 + (rand(gs + i * 29.3) - 0.5) * 0.08;
  const r2 = 2.6 + (rand(gs + i * 35.9) - 0.5) * 0.2;
  minors.push(
    poly(shardPoints(gs + i * 27.1, 1.7 * scale, 1.35 * scale, theta2, r2, 0.75), '#0a0f16', 1, '#4a6a80', 0.26)
  );
}

// Gyre rings in the throat: nested faceted apertures.
const gyres = [];
for (const [k, r] of [[0, 1.58], [1, 1.28], [2, 1.0]]) {
  const pts = [];
  for (let s = 0; s < 9; s++) {
    const a = (s / 9) * Math.PI * 2 + k * 0.35;
    const wobble = 1 + (rand(gs + 93 + k * 31.7 + s * 3.1) - 0.5) * 0.09;
    pts.push(`${s ? 'L' : 'M'}${px(Math.cos(a) * r * wobble)} ${py(Math.sin(a) * r * wobble)}`);
  }
  gyres.push(
    `<path d="${pts.join(' ')} Z" fill="none" stroke="#4dd0ff" stroke-opacity="${(0.16 + k * 0.1).toFixed(2)}" stroke-width="${1.2 + k * 0.5}"/>`
  );
}

// Halo geometry: matches HALO_Y / HALO_TILT / torus 2.0 in LatticeModel.
const ringRx = (3.0 * SCALE).toFixed(1);
const ringRy = (3.0 * SCALE * 0.43).toFixed(1);
const haloCy = (CY - 3.3 * SCALE).toFixed(1);

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-hidden="true" preserveAspectRatio="xMidYMid slice">
  <title>Dark Lattice</title>
  <!--
    GENERATED by tools/poster.mjs — do not hand-edit.

    Composed still shown for reduced motion, WebGL failure and
    JavaScript-disabled visits: the sealed v7 crowned convergence,
    front-on — jagged obsidian crown, recessed cyan core, amber halo.
    Constants mirror LatticeModel.
  -->
  <defs>
    <radialGradient id="throat" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#4dd0ff" stop-opacity="0.9"/>
      <stop offset="22%" stop-color="#4dd0ff" stop-opacity="0.34"/>
      <stop offset="55%" stop-color="#173a4d" stop-opacity="0.18"/>
      <stop offset="100%" stop-color="#080b10" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="kernel" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#dff9ff"/>
      <stop offset="45%" stop-color="#4dd0ff"/>
      <stop offset="100%" stop-color="#4dd0ff" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="haloGrad" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#d9a75e" stop-opacity="0.25"/>
      <stop offset="35%" stop-color="#ffeac2" stop-opacity="0.95"/>
      <stop offset="65%" stop-color="#ffeac2" stop-opacity="1"/>
      <stop offset="100%" stop-color="#d9a75e" stop-opacity="0.3"/>
    </linearGradient>
    <radialGradient id="vignette" cx="50%" cy="46%" r="72%">
      <stop offset="40%" stop-color="#080b10" stop-opacity="0"/>
      <stop offset="100%" stop-color="#04060a" stop-opacity="0.9"/>
    </radialGradient>
    <filter id="soften" x="-25%" y="-25%" width="150%" height="150%">
      <feGaussianBlur stdDeviation="5"/>
    </filter>
    <filter id="softenWide" x="-35%" y="-35%" width="170%" height="170%">
      <feGaussianBlur stdDeviation="18"/>
    </filter>
  </defs>

  <rect width="${W}" height="${H}" fill="#080b10"/>

  <!-- The convergence light, bleeding out of the throat. -->
  <circle cx="${CX}" cy="${CY}" r="${(2.4 * SCALE).toFixed(0)}" fill="url(#throat)"/>

  <!-- The crown: infill layer, gyres, the kernel eye, majors over it. -->
  <g>
${minors.map((s) => `    ${s}`).join(NL)}
  </g>
  <g>
${gyres.map((s) => `    ${s}`).join(NL)}
  </g>
  <!-- The kernel: the recessed eye. -->
  <circle cx="${CX}" cy="${CY}" r="${(0.5 * SCALE).toFixed(0)}" fill="url(#kernel)"/>
  <g>
${majors.map((s) => `    ${s}`).join(NL)}
  </g>

  <!-- Halo — the silent crown: one hair-thin band, no glare. -->
  <g transform="translate(${CX} ${haloCy}) rotate(-5)">
    <ellipse rx="${ringRx}" ry="${ringRy}" fill="none" stroke="url(#haloGrad)" stroke-width="2.4"
             opacity="0.3" filter="url(#soften)"/>
    <ellipse rx="${ringRx}" ry="${ringRy}" fill="none" stroke="url(#haloGrad)" stroke-width="1.1"
             opacity="0.85"/>
  </g>

  <rect width="${W}" height="${H}" fill="url(#vignette)"/>
</svg>
`;

await writeFile('public/fallback/hero-poster.svg', svg);
console.log(`wrote public/fallback/hero-poster.svg — v7 crowned convergence`);
